import { chromium, expect } from '@playwright/test';
import { mkdir, writeFile } from 'node:fs/promises';

// Esta suite usa los servicios reales de scripts/test-sprint2.mjs, con otra base de datos.
const base = process.env.E2E_URL || 'http://localhost:5174';
if (new URL(base).port === '5173') throw new Error('Usa el entorno aislado de pruebas en 5174.');
const groupId = 'b1300000-0000-4000-8000-000000000001', password = 'LuminaLocal2026!';
const results = [], errors = [], nativeDialogs = [], contexts = [];
await mkdir('analysis/validation', { recursive: true });
const browser = await chromium.launch({ channel: process.env.BROWSER_CHANNEL || 'msedge', headless: true });
async function session(email, mobile = false) {
  const ctx = await browser.newContext({ viewport: mobile ? { width: 390, height: 844 } : { width: 1440, height: 1000 }, reducedMotion: 'reduce' });
  contexts.push(ctx);
  const page = await ctx.newPage();
  page.on('pageerror', e => errors.push(e.message));
  page.on('dialog', async d => { nativeDialogs.push(d.type()); await d.dismiss(); });
  await page.goto(base + '/login');
  if (email) {
    await page.getByLabel('Correo institucional').fill(email);
    await page.getByLabel('Contraseña', { exact: true }).fill(password);
    await page.getByRole('button', { name: 'Iniciar sesión', exact: true }).click();
    await expect(page).toHaveURL(base + '/');
  }
  return { ctx, page };
}
async function join(page, message) {
  const card = page.locator('.post-card').filter({ hasText: '¿Repasamos SOLID y patrones juntos?' });
  await card.getByRole('button', { name: 'Me interesa' }).click();
  const dialog = page.getByRole('dialog');
  await dialog.getByLabel('Preséntate al grupo').fill(message);
  await dialog.getByRole('button', { name: 'Enviar solicitud' }).click();
  await expect(page.getByRole('dialog', { name: 'Solicitud enviada' })).toBeVisible();
  await expect(dialog.getByRole('status')).toHaveText('Solicitud enviada con éxito');
  return dialog;
}
let lastPage;
try {
  const student = await session(); const page = lastPage = student.page;
  let loginCalls = 0;
  page.on('request', r => { if (r.url().endsWith('/auth/login')) loginCalls++; });
  await page.getByRole('button', { name: 'Iniciar sesión', exact: true }).click();
  await expect(page.getByText('Ingresa tu correo institucional.', { exact: true })).toBeVisible();
  await expect(page.getByText('Ingresa tu contraseña.', { exact: true })).toBeVisible();
  expect(loginCalls).toBe(0);
  await page.getByLabel('Correo institucional').fill('externo@gmail.com');
  await page.getByLabel('Contraseña', { exact: true }).fill('incorrecta');
  await page.getByRole('button', { name: 'Iniciar sesión', exact: true }).click();
  await expect(page.getByText(/Usa un correo @aloe/)).toBeVisible(); expect(loginCalls).toBe(0);
  await page.getByLabel('Correo institucional').fill('usuario.prueba@aloe.ulima.edu.pe');
  await page.getByRole('button', { name: 'Iniciar sesión', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('Correo o contraseña incorrectos');
  await expect(page).toHaveURL(base + '/login');
  results.push('Login: campos vacíos, correo externo y contraseña incorrecta no ingresan');
  await page.getByLabel('Contraseña', { exact: true }).fill(password);
  await page.getByRole('button', { name: 'Iniciar sesión', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Hola, Usuario.' })).toBeVisible();
  expect((await student.ctx.cookies()).find(c => c.name === 'access_token').httpOnly).toBe(true);
  await page.reload(); await expect(page.getByRole('heading', { name: 'Hola, Usuario.' })).toBeVisible();
  results.push('Login real y sesión persistente al recargar');
  await page.screenshot({ path: 'analysis/validation/sprint2-inicio.png', fullPage: true });
  const card = page.locator('.post-card').filter({ hasText: '¿Repasamos SOLID y patrones juntos?' });
  await card.getByRole('button', { name: 'Me interesa' }).click();
  await page.getByRole('dialog').getByRole('button', { name: 'Enviar solicitud' }).click();
  await expect(page.getByRole('dialog').getByRole('alert')).toContainText('Escribe un mensaje');
  await page.getByRole('dialog').getByRole('link', { name: 'Ver detalle del grupo' }).click();
  await expect(page.getByRole('heading', { name: 'Grupo de Ingeniería de Software II', exact: true })).toBeVisible();
  await expect(page.getByText('Administrador', { exact: true }).last()).toBeVisible();
  await page.screenshot({ path: 'analysis/validation/sprint2-detalle.png', fullPage: true });
  await page.getByRole('button', { name: 'Enviar solicitud', exact: true }).click();
  const dialog = page.getByRole('dialog');
  await dialog.getByLabel('Preséntate al grupo').fill('Me gustaría repasar patrones de diseño con ustedes.');
  await dialog.getByRole('button', { name: 'Enviar solicitud', exact: true }).click();
  await expect(page.getByRole('dialog', { name: 'Solicitud enviada' })).toBeVisible();
  await page.screenshot({ path: 'analysis/validation/sprint2-exito.png' });
  await dialog.getByRole('button', { name: 'Entendido' }).click();
  await expect(page.getByRole('button', { name: 'Solicitud pendiente' })).toBeDisabled();
  await page.reload(); await expect(page.getByRole('button', { name: 'Solicitud pendiente' })).toBeDisabled();
  const duplicate = await student.ctx.request.post(base + `/groups/${groupId}/join-requests`, { data: { message: 'Otra solicitud' } });
  expect(duplicate.status()).toBe(409);
  results.push('Detalle, mensaje obligatorio, envío real, modal de éxito y bloqueo de duplicado');
  const admin = await session('administrador.prueba@aloe.ulima.edu.pe'); lastPage = admin.page;
  await admin.page.goto(base + '/solicitudes');
  await expect(admin.page.locator('.join-request-card')).toHaveCount(1);
  await expect(admin.page.locator('.join-request-card')).toContainText('Usuario');
  await admin.page.screenshot({ path: 'analysis/validation/sprint2-solicitudes.png', fullPage: true });
  await admin.page.getByRole('button', { name: 'Aceptar solicitud de Usuario' }).click();
  await expect(admin.page.locator('.toast')).toContainText('Solicitud aceptada exitosamente');
  await expect(admin.page.locator('.join-request-card')).toHaveCount(0);
  await page.reload(); await expect(page.getByRole('heading', { name: /Integrantes/ })).toBeVisible();
  await expect(page.getByRole('button', { name: 'Enviar solicitud', exact: true })).toHaveCount(0);
  await page.goto(base + '/grupos'); await expect(page.locator('.group-card')).toContainText('Grupo de Ingeniería de Software II');
  results.push('Administrador acepta y el nuevo miembro aparece en Mis grupos');
  const ana = await session('ana.prueba@aloe.ulima.edu.pe'); lastPage = ana.page;
  const success = await join(ana.page, 'Quiero preparar la práctica.');
  await success.getByRole('button', { name: 'Entendido' }).click();
  await admin.page.reload();
  await admin.page.getByRole('button', { name: 'Rechazar solicitud de Ana Torres' }).click();
  await expect(admin.page.locator('.toast')).toContainText('Solicitud rechazada exitosamente');
  await expect(admin.page.getByRole('heading', { name: 'No hay solicitudes pendientes por revisar' })).toBeVisible();
  const anaGroup = await ana.ctx.request.get(base + `/groups/${groupId}`); expect((await anaGroup.json()).my_status).toBe('none');
  results.push('Administrador rechaza, lista se actualiza y no se crea membresía');
  let logouts = 0; page.on('request', r => { if (r.url().endsWith('/auth/logout')) logouts++; });
  await page.getByRole('button', { name: 'Cerrar sesión', exact: true }).click();
  await page.getByRole('dialog').getByRole('button', { name: 'Seguir aquí' }).click(); expect(logouts).toBe(0);
  await page.route('**/auth/logout', route => route.abort());
  await page.getByRole('button', { name: 'Cerrar sesión', exact: true }).click();
  await page.getByRole('dialog').getByRole('button', { name: 'Cerrar sesión', exact: true }).click();
  await expect(page.getByRole('alert')).toContainText('No pudimos conectar');
  await expect(page).toHaveURL(base + '/grupos');
  await page.unroute('**/auth/logout');
  await page.getByRole('button', { name: 'Cerrar sesión', exact: true }).click();
  await page.screenshot({ path: 'analysis/validation/sprint2-cerrar-sesion.png' });
  await page.keyboard.press('Escape'); await expect(page.getByRole('dialog')).toHaveCount(0);
  await page.getByRole('button', { name: 'Cerrar sesión', exact: true }).click();
  await page.getByRole('dialog').getByRole('button', { name: 'Cerrar sesión', exact: true }).click();
  await expect(page).toHaveURL(base + '/login');
  await page.goto(base + '/solicitudes'); await expect(page).toHaveURL(base + '/login');
  results.push('Logout: cancelar, Escape, fallo de red conserva sesión y confirmar protege rutas');
  const mobile = await session('ana.prueba@aloe.ulima.edu.pe', true); lastPage = mobile.page;
  expect(await mobile.page.evaluate(() => document.documentElement.scrollWidth > innerWidth)).toBe(false);
  const mobileDialog = await join(mobile.page, 'Me gustaría intentarlo nuevamente.');
  const bounds = await mobileDialog.boundingBox(); expect(bounds.x).toBeGreaterThanOrEqual(0); expect(bounds.x + bounds.width).toBeLessThanOrEqual(390);
  expect(await mobileDialog.locator('.confirmation-symbol').evaluate(e => getComputedStyle(e).animationName)).toBe('none');
  await mobile.page.screenshot({ path: 'analysis/validation/sprint2-movil.png', fullPage: true });
  await mobileDialog.getByRole('button', { name: 'Entendido' }).click();
  await mobile.page.getByRole('button', { name: 'Abrir menú' }).click();
  await mobile.page.getByRole('link', { name: 'Solicitudes', exact: true }).click();
  await expect(mobile.page.getByRole('heading', { name: 'No hay solicitudes pendientes por revisar' })).toBeVisible();
  results.push('Móvil 390px sin desbordamiento, menú operativo y movimiento reducido');
  expect(nativeDialogs).toEqual([]); expect(errors).toEqual([]);
  results.push('Sin alert/confirm/prompt nativos ni excepciones JavaScript');
} catch (e) {
  console.error(e); process.exitCode = 1; results.push('FAIL: ' + e.message);
  await lastPage?.screenshot({ path: 'analysis/validation/sprint2-error.png', fullPage: true }).catch(() => {});
} finally {
  await browser.close();
  await writeFile('analysis/validation/sprint2.json', JSON.stringify({ status: process.exitCode ? 'FAIL' : 'PASS', results, errors, nativeDialogs }, null, 2));
  console.log(results.join('\n'));
}
